//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCade.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniCade.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Consoles: .
        /// </summary>
        internal static string AvailableConsoles {
            get {
                return ResourceManager.GetString("AvailableConsoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Users.
        /// </summary>
        internal static string AvailableUsers {
            get {
                return ResourceManager.GetString("AvailableUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options: Exit: (x), Global Rescan (r):, Console Info: (i) &lt;console&gt;, Switch User (s).
        /// </summary>
        internal static string CmdConsoleSelectionOptions {
            get {
                return ResourceManager.GetString("CmdConsoleSelectionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console: .
        /// </summary>
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Info: .
        /// </summary>
        internal static string ConsoleInfo {
            get {
                return ResourceManager.GetString("ConsoleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current directory is write protected. The interface will now exit.
        /// </summary>
        internal static string CurrentDirectoryWriteProtected {
            get {
                return ResourceManager.GetString("CurrentDirectoryWriteProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error: Database File is corrupt.
        /// </summary>
        internal static string DatabaseCorrupt {
            get {
                return ResourceManager.GetString("DatabaseCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Not Found: .
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator Path: .
        /// </summary>
        internal static string EmulatorPath {
            get {
                return ResourceManager.GetString("EmulatorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Database
        ///.
        /// </summary>
        internal static string ErrorSavingDatabase {
            get {
                return ResourceManager.GetString("ErrorSavingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid game.
        /// </summary>
        internal static string InvalidGame {
            get {
                return ResourceManager.GetString("InvalidGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Param: .
        /// </summary>
        internal static string LaunchParam {
            get {
                return ResourceManager.GetString("LaunchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Accepted.
        /// </summary>
        internal static string PasswordAccepted {
            get {
                return ResourceManager.GetString("PasswordAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password (Type &apos;x&apos; to exit).
        /// </summary>
        internal static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username (Type &apos;x&apos; to exit).
        /// </summary>
        internal static string PleaseEnterUsername {
            get {
                return ResourceManager.GetString("PleaseEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Press any key to return to previous menu
        ///.
        /// </summary>
        internal static string PressAnyKeyToReturnToPreviousMenu {
            get {
                return ResourceManager.GetString("PressAnyKeyToReturnToPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: .
        /// </summary>
        internal static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom Extension: .
        /// </summary>
        internal static string RomExtension {
            get {
                return ResourceManager.GetString("RomExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom Path: .
        /// </summary>
        internal static string RomPath {
            get {
                return ResourceManager.GetString("RomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The interface will now exit.
        /// </summary>
        internal static string TheInterfaceWillNowExit {
            get {
                return ResourceManager.GetString("TheInterfaceWillNowExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniCade Cloud connection Error.
        /// </summary>
        internal static string UniCadeCloudConnectionError {
            get {
                return ResourceManager.GetString("UniCadeCloudConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Exists.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not found.
        /// </summary>
        internal static string UsernameNotFound {
            get {
                return ResourceManager.GetString("UsernameNotFound", resourceCulture);
            }
        }
    }
}
